version: '3'
services:
        strapiback:
                image: node:14.16.0
                stdin_open: true
                volumes:
                        - ./strapi-back/:/usr/src/app
                working_dir: /usr/src/app
                ports:
                        - 1337:1337
                command: bash -c "npm install && yarn develop"
